create table employee(
    id bigint generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    midlle_name varchar(100),
    email varchar(100) unique not null
);