DROP table if exists authors;

CREATE TABLE authors (
  id bigint generated by default as identity primary key,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  birthdate date NOT NULL,
  added timestamp NOT NULL DEFAULT NOW()
);


Drop table if exists posts;
CREATE TABLE posts (
  id bigint generated by default as identity primary key,
  author_id bigint NOT NULL,
  title varchar(255) NOT NULL,
  description varchar(500) NOT NULL,
  content text NOT NULL,
  date date NOT NULL,
  constraint fk_posts_authors foreign key(author_id) references authors(id)
);